# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Symbol-Values
version:      1.03
version_from: lib/Symbol/Values.pm
installdirs:  site
requires:
    Carp:                          1
    Symbol:                        1
    Tie::Scalar:                   1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
